# Generated by Django 6.0.4 on 2026-04-25 18:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content_text', models.TextField(blank=True, verbose_name='Текст')),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='learning/images/', verbose_name='Изображение')),
                ('content_audio', models.FileField(blank=True, null=True, upload_to='learning/audio/', verbose_name='Аудиофайл')),
                ('title', models.CharField(max_length=255, verbose_name='Название группы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа сопоставления',
                'verbose_name_plural': 'Группы сопоставления',
                'ordering': ['matching', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MatchingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('mode', models.CharField(choices=[('pair', 'Один к одному'), ('group', 'Один ко многим')], max_length=20, verbose_name='Режим сопоставления')),
            ],
            options={
                'verbose_name': 'Задание на сопоставление',
                'verbose_name_plural': 'Задания на сопоставление',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название модуля')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='modules/covers/', verbose_name='Обложка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OrderingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Задание на последовательность',
                'verbose_name_plural': 'Задания на последовательность',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='subjects/covers/', verbose_name='Обложка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content_text', models.TextField(blank=True, verbose_name='Текст')),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='learning/images/', verbose_name='Изображение')),
                ('content_audio', models.FileField(blank=True, null=True, upload_to='learning/audio/', verbose_name='Аудиофайл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Преподаватель'), ('learner', 'Ученик')], default='learner', help_text='Показывает роль пользователя в системе.', max_length=20, verbose_name='Роль')),
                ('avatar', models.ImageField(blank=True, help_text='Фотография профиля пользователя.', null=True, upload_to='users/avatars/', verbose_name='Аватар')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: 3А, 4Б или подготовительная группа.', max_length=255, verbose_name='Название класса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('students', models.ManyToManyField(blank=True, help_text='Ученики обучающиеся в этом классе.', related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Обучающиеся')),
                ('teacher', models.ForeignKey(help_text='Учитель, отвечающий за этот класс.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Учебные классы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MatchingGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content_text', models.TextField(blank=True, verbose_name='Текст')),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='learning/images/', verbose_name='Изображение')),
                ('content_audio', models.FileField(blank=True, null=True, upload_to='learning/audio/', verbose_name='Аудиофайл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.matchinggroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Элемент группы',
                'verbose_name_plural': 'Элементы группы',
                'ordering': ['group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('left_text', models.TextField(blank=True, verbose_name='Левый текст')),
                ('left_image', models.ImageField(blank=True, null=True, upload_to='matching/left/images/', verbose_name='Левое изображение')),
                ('left_audio', models.FileField(blank=True, null=True, upload_to='matching/left/audio/', verbose_name='Левый аудиофайл')),
                ('right_text', models.TextField(blank=True, verbose_name='Правый текст')),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='matching/right/images/', verbose_name='Правое изображение')),
                ('right_audio', models.FileField(blank=True, null=True, upload_to='matching/right/audio/', verbose_name='Правый аудиофайл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='core.matchingtask', verbose_name='Сопоставление')),
            ],
            options={
                'verbose_name': 'Пара сопоставления',
                'verbose_name_plural': 'Пары сопоставления',
                'ordering': ['matching', 'order'],
            },
        ),
        migrations.AddField(
            model_name='matchinggroup',
            name='matching',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.matchingtask', verbose_name='Сопоставление'),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название уровня')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='core.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OrderingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content_text', models.TextField(blank=True, verbose_name='Текст')),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='learning/images/', verbose_name='Изображение')),
                ('content_audio', models.FileField(blank=True, null=True, upload_to='learning/audio/', verbose_name='Аудиофайл')),
                ('correct_order', models.PositiveIntegerField(verbose_name='Правильный порядок')),
                ('ordering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.orderingtask', verbose_name='Последовательность')),
            ],
            options={
                'verbose_name': 'Элемент последовательности',
                'verbose_name_plural': 'Элементы последовательности',
                'ordering': ['ordering', 'correct_order'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.subject', verbose_name='Предмет'),
        ),
        migrations.CreateModel(
            name='ClassroomSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_subjects', to='core.classroom', verbose_name='Класс')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_subjects', to='core.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет класса',
                'verbose_name_plural': 'Предметы классов',
            },
        ),
        migrations.CreateModel(
            name='SubjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_started', models.BooleanField(default=False, verbose_name='Начат')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершён')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='core.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Прогресс по предмету',
                'verbose_name_plural': 'Прогресс по предметам',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('instruction', models.TextField(blank=True, verbose_name='Инструкция')),
                ('task_type', models.CharField(choices=[('test', 'Тест'), ('matching', 'Сопоставление'), ('ordering', 'Правильная последовательность'), ('audio', 'Аудиозапись')], max_length=30, verbose_name='Тип задания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.level', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.AddField(
            model_name='orderingtask',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_task', to='core.task', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='matchingtask',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_task', to='core.task', verbose_name='Задание'),
        ),
        migrations.CreateModel(
            name='AudioTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content_text', models.TextField(blank=True, verbose_name='Текст')),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='learning/images/', verbose_name='Изображение')),
                ('content_audio', models.FileField(blank=True, null=True, upload_to='learning/audio/', verbose_name='Аудиофайл')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_task', to='core.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Задание с аудиозаписью',
                'verbose_name_plural': 'Задания с аудиозаписью',
            },
        ),
        migrations.CreateModel(
            name='AudioSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название аудиозаписи')),
                ('audio_file', models.FileField(upload_to='audio-submissions/', verbose_name='Аудиофайл')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_submissions', to='core.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Аудиоответ',
                'verbose_name_plural': 'Аудиоответы',
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('locked', 'Закрыто'), ('unlocked', 'Открыто'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='locked', max_length=30, verbose_name='Статус')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('last_answer_data', models.JSONField(blank=True, null=True, verbose_name='Последний ответ')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='core.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Прогресс по заданию',
                'verbose_name_plural': 'Прогресс по заданиям',
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content_text', models.TextField(blank=True, verbose_name='Текст')),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='learning/images/', verbose_name='Изображение')),
                ('content_audio', models.FileField(blank=True, null=True, upload_to='learning/audio/', verbose_name='Аудиофайл')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.testquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ теста',
                'verbose_name_plural': 'Ответы теста',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('allow_multiple_answers', models.BooleanField(default=False, verbose_name='Разрешить несколько правильных ответов')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_task', to='core.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.AddField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.testtask', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='LevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_unlocked', models.BooleanField(default=False, verbose_name='Открыт')),
                ('is_started', models.BooleanField(default=False, verbose_name='Начат')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершён')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='core.level', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Прогресс по уровню',
                'verbose_name_plural': 'Прогресс по уровням',
                'constraints': [models.UniqueConstraint(fields=('learner', 'level'), name='unique_level_progress_per_learner')],
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_unlocked', models.BooleanField(default=False, verbose_name='Открыт')),
                ('is_started', models.BooleanField(default=False, verbose_name='Начат')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершён')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progresses', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='core.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Прогресс по модулю',
                'verbose_name_plural': 'Прогресс по модулям',
                'constraints': [models.UniqueConstraint(fields=('learner', 'module'), name='unique_module_progress_per_learner')],
            },
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('subject', 'slug'), name='unique_module_slug_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='classroomsubject',
            constraint=models.UniqueConstraint(fields=('classroom', 'subject'), name='unique_subject_per_classroom'),
        ),
        migrations.AddConstraint(
            model_name='subjectprogress',
            constraint=models.UniqueConstraint(fields=('learner', 'subject'), name='unique_subject_progress_per_learner'),
        ),
        migrations.AddConstraint(
            model_name='audiosubmission',
            constraint=models.UniqueConstraint(fields=('learner', 'task'), name='unique_audio_submission_per_task'),
        ),
        migrations.AddConstraint(
            model_name='taskprogress',
            constraint=models.UniqueConstraint(fields=('learner', 'task'), name='unique_task_progress_per_learner'),
        ),
    ]
