# Generated by Django 6.0.4 on 2026-04-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testanswer',
            options={'verbose_name': 'Ответ теста', 'verbose_name_plural': 'Ответы теста'},
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='order',
        ),
        migrations.AddField(
            model_name='audiotask',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='matchingtask',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='orderingtask',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='testtask',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
