# Generated by Django 6.0.4 on 2026-04-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_testanswer_options_remove_testanswer_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotask',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='matchingtask',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='orderingtask',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
    ]
