# Generated by Django 6.0.4 on 2026-04-24 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_classroom_options_alter_classroom_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['name'], 'verbose_name': 'Класс', 'verbose_name_plural': 'Учебные классы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(help_text='Например: 3А, 4Б или подготовительная группа.', max_length=255, verbose_name='Название класса'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Ученики обучающиеся в этом классе.', related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Обучающиеся'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(help_text='Учитель, отвечающий за этот класс.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Фотография профиля пользователя.', null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Преподаватель'), ('learner', 'Ученик')], default='learner', help_text='Показывает роль пользователя в системе.', max_length=20, verbose_name='Роль'),
        ),
    ]
