# Generated by Django 6.0.4 on 2026-04-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_level_description_orderingtask_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderingtask',
            name='title',
        ),
        migrations.AddField(
            model_name='orderingtask',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
