# Generated by Django 6.0.4 on 2026-04-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_orderingtask_title_orderingtask_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingtask',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
