# Generated by Django 6.0.4 on 2026-04-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orderingtask_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingtask',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
