# Generated by Django 6.0.4 on 2026-06-15 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_orderingtask_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITutorInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_status', models.CharField(choices=[('wrong', 'Wrong'), ('partial', 'Partial'), ('correct', 'Correct')], max_length=20)),
                ('student_answer', models.JSONField(default=dict)),
                ('ai_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tutor_interactions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tutor_interactions', to='core.task')),
                ('task_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tutor_interactions', to='core.taskprogress')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
