# Generated by Django 6.0.4 on 2026-06-15 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aitutorinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_conversations', to='core.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Диалог с ИИ-тьютором',
                'verbose_name_plural': 'Диалоги с ИИ-тьютором',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('role', models.CharField(choices=[('user', 'Ученик'), ('assistant', 'ИИ-тьютор')], max_length=20, verbose_name='Роль')),
                ('content', models.TextField(verbose_name='Текст')),
                ('answer_snapshot', models.JSONField(blank=True, null=True, verbose_name='Снимок ответа')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.tutorconversation', verbose_name='Диалог')),
            ],
            options={
                'verbose_name': 'Сообщение тьютора',
                'verbose_name_plural': 'Сообщения тьютора',
                'ordering': ['conversation', 'created_at', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='AITutorInteraction',
        ),
        migrations.AddConstraint(
            model_name='tutorconversation',
            constraint=models.UniqueConstraint(fields=('learner', 'task'), name='unique_tutor_conversation_per_task'),
        ),
    ]
